[[9314304, "Traceback (most recent call last):\r\n  File \"C:\\Users\\Admin\\Desktop\\YandexLyceum\\Test system\\test-system\\program_testing\\source_solution\\thread_1\\solution.py\", line 3, in <module>\r\n    os.remove('db/test_system.db')\r\nPermissionError: [WinError 32] \u2568\u042f\u2564\u0410\u2568\u255b\u2564\u0416\u2568\u2561\u2564\u0411\u2564\u0411 \u2568\u255c\u2568\u2561 \u2568\u255d\u2568\u255b\u2568\u2562\u2568\u2561\u2564\u0412 \u2568\u2510\u2568\u255b\u2568\u2557\u2564\u0413\u2564\u0417\u2568\u2555\u2564\u0412\u2564\u041c \u2568\u2524\u2568\u255b\u2564\u0411\u2564\u0412\u2564\u0413\u2568\u2510 \u2568\u2551 \u2564\u0414\u2568\u2591\u2568\u2563\u2568\u2557\u2564\u0413, \u2564\u0412\u2568\u2591\u2568\u2551 \u2568\u2551\u2568\u2591\u2568\u2551 \u2564\u041d\u2564\u0412\u2568\u255b\u2564\u0412 \u2564\u0414\u2568\u2591\u2568\u2563\u2568\u2557 \u2568\u2556\u2568\u2591\u2568\u255c\u2564\u041f\u2564\u0412 \u2568\u2524\u2564\u0410\u2564\u0413\u2568\u2502\u2568\u2555\u2568\u255d \u2568\u2510\u2564\u0410\u2568\u255b\u2564\u0416\u2568\u2561\u2564\u0411\u2564\u0411\u2568\u255b\u2568\u255d: 'db/test_system.db'", null, 0.062399864196777344]]